name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system
      run: |
        sudo apt update && sudo apt-get install -y ca-certificates curl
    - name: Install python
      run: |
        python -m pip install --upgrade pip
        pip install "netCDF4<1.6.0"
    - name: Unit test
      run: |
        python -m unittest discover -p 'test_*.py'
